### ISSUE TITLE
Длительное нажатие

### ISSUE THREAD

**Issue by drblez** [Pshatsillo/openHABMegaDevice#1]
Приветствую!

Начиная с версии мегадевайса 3.42 поддерживается опция длительного нажатия, которая проявляет себя в отправке на сервер запроса в котором параметр m=2. Возможно ли сделать опциональное отключение обработки таких запросов? Спасибо!

**Comment by Pshatsillo** [comment]
Здравствуйте. Я не разработчик устройства, я автор плагина для openhab. Плагином данная комманда не поддерживается, т.к. совершенно не имеет смысла. Связаться с разработчиком можно на сайте ab-log.ru

**Comment by drblez** [comment]
Я имел ввиду, что надо игнорировать запросы от устройства в которых m=2

вс, 7 авг. 2016 г., 1:40 Pshatsillo notifications@github.com:

**Comment by drblez** [comment]
Сейчас это выглядит так: порт включается, приходит запрос и через некоторое
время приходит еще один. В опенхабе получается два события ON

вс, 7 авг. 2016 г., 1:40 Pshatsillo notifications@github.com:

**Comment by Pshatsillo** [comment]
Понял, исправлю, видимо проверка не учитывает цифру после m=
